server:
  port: 8090

spring:
  application:
    name: shoe-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop?currentSchema=core
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
#        http://localhost:8080/realms/ecommerce/.well-known/openid-configuration
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
          jwk-set-uri: http://localhost:8080/realms/ecommerce/protocol/openid-connect/certs
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**
    livereload:
      enabled: true

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: ecommerce
  resource: shop-be
  public-client: true
  keycloak.principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.boot.devtools: DEBUG
